[book]
authors = ["Satheeshsk369"]
language = "en"
multilingual = false
src = "src"
title = "dncs"

[output.html]
mathjax-support = true

[output.html.playground]
editable = false
line-numbers = false
runnable = false
